name: Deploy 12 Days ALife

on:
  schedule:
    - cron:  '1-59/2 * * * *'

env:
  BASE_BRANCH_NAME: 12-days-alife
  HOSTING_BRANCH_NAME: gh-pages-12-days-alife
  LOCAL_BRANCH_NAME: gh-pages-local-12-days-alife

jobs:
  Echo:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo
        run: |
          python 12DaysAlife.py
