name: Deploy to GitHub Pages

on:
  push:
    branches: [ add-github-actions ]
  workflow_dispatch:

jobs:
  Build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # I think we can remove using devmasx/merge-branch, by doing: `$cd $GITHUB_WORKSPACE`, merge and push with github.token
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '2.7'
      - name: Checkout
        run: |
          cd $GITHUB_WORKSPACE
          git fetch
          git checkout gh-pages
      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install markdown
          python makeAllEditions.py
      - name: Commit
        run: |
          git add .
          git commit -m 'Generated static html files'

# for using Python in workflow, see following links: 
# - https://docs.github.com/actions/automating-builds-and-tests/building-and-testing-python#using-the-python-starter-workflow
# - https://github.com/actions/setup-python