name: Deploy to GitHub Pages

on:
  push:
    branches: [ add-github-actions ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # I think we can remove using devmasx/merge-branch, by doing: `$cd $GITHUB_WORKSPACE`, merge and push with github.token
      - uses: actions/checkout@v2
      - name: Deploy
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: add-github-actions
          target_branch: gh-pages
          github_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
      - run: python makeAllEditions.py
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4.2.0
        with:
          commit_message: makeAllEditions.py
          branch: gh-pages